name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: CGO_ENABLED=1 go build -o cmdo-${{ matrix.goos }}-${{ matrix.goarch }}